
#Wytham woods crop
#pred_forest_path: 'results/wytham_crop_train.laz' # path to predicted forest
pred_forest_path: 'data/forainet_results/wytham_crop_train_out.laz'
benchmark_forest_path: 'data/wytham_crop_small/input/wytham_crop_train.laz' # path to ground truth benchmark dataset

#tuwien_test
#benchmark_forest_path: "../TreeLearnSemiSup/dataset_for_semi_sup/tuwien_test.las"
#pred_forest_path: 'results/tuwien_test_out.laz'
#tree_nums_used_for_evaluation_path: 'data/extra/evaluated_trees.txt' # path to txt file consisting of all tree numbers to be taken into account for evaluation

min_iou_for_match: 0.2 # minimumn pointwise iou between predicted and ground truth tree for hungarian matching

voxel_sizes: [0.3, 0.4, 0.5]

partitions:
  xy_partition_relative: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1] # radial dvision of each tree into segments (see paper for details)
  z_partition_relative: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1] # vertical dvision of each tree into segments (see paper for details)
  xy_partition_absolute: [0, 1.2, 2.4, 3.6, 4.8, 6, 7.2, 8.4, 9.6, 10.8, 15] # radial dvision of each tree into segments (see paper for details)
  z_partition_absolute: [0, 3.8, 7.6, 11.4, 15.2, 19, 22.8, 26.6, 30.4, 34.2, 40] # vertical dvision of each tree into segments (see paper for details)
